gui: Don't initialise GTK socket server if we're not doing GTK.
```
gcc -c -I. -Iproto -DHAVE_CONFIG_H -DFEAT_GUI_MOTIF   -Wdate-time   -g -O2 -Werror=implicit-function-declaration -ffile-prefix-map=/tmp/evi-build/evi-10.0.0000=. -fstack-protector-strong -fstack-clash-protection -Wformat -Werror=format-security -fcf-protection -DSYS_VIMRC_FILE=\"/etc/evi/evirc\" -DSYS_GVIMRC_FILE=\"/etc/evi/gevirc\"  -D_REENTRANT -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1        -o objects/gui.o gui.c
gui.c: In function 'gui_start':
gui.c:158:9: error: implicit declaration of function 'gui_gtk_init_socket_server' [-Wimplicit-function-declaration]
  158 |         gui_gtk_init_socket_server();
      |         ^~~~~~~~~~~~~~~~~~~~~~~~~~
make[3]: *** [Makefile:3311: objects/gui.o] Error 1
```